spring:
 application:
  name: "configserver"
 profiles:
   active:
     - native
      #- git

 cloud:
   config:
     server:
       native:
         search-locations:
          # - "classpath:/config"
           - "file:///C://config"
#        git:
#          uri: "*****"
#          #username: *****
#          #password: ****
#          default-label: main # this like what branch this file there
#          timeout: 5
#          clone-on-start: true
#          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071


